title: Mohamed Shaheen
Phone: +971 562747525
Email: zhaheen21@gmail.com
Address: Dubai, United Arab Emirates.
LinkedIn: https://www.linkedin.com/in/shaheen21/
logo: /assets/img/Mohamed shaheen-Photo.jpg
description: Mohamed Shaheen Portfolio
show_downloads: true
theme: jekyll-theme-minimal
