title: Mohamed Shaheen
logo: /assets/img/Mohamed shaheen-Photo.jpg
description: >
  Phone: +971 562747525<br>
  Email: zhaheen21@gmail.com<br>
  Address: Dubai, United Arab Emirates.<br>
  LinkedIn: https://linkedin.com/in/shaheen21/
show_downloads: false
theme: jekyll-theme-minimal
