title: Mohamed Shaheen
logo: /assets/img/Mohamed shaheen-Photo.jpg
description: |
  Phone: +971 562747525 |
  Email: zhaheen21@gmail.com |
  Address: Dubai, United Arab Emirates. |
  LinkedIn: https://linkedin.com/in/shaheen21/
show_downloads: true
theme: jekyll-theme-minimal
